# Generated by Django 5.2.3 on 2026-03-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status_order_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_quantity',
            new_name='total_items',
        ),
    ]
